[{"name": "test.test_subfigures.Subplots.test_calls", "status": "passed", "message": "", "passed": true, "points": ["p03-10.1"], "backtrace": []}, {"name": "test.test_subfigures.Subplots.test_method_calls", "status": "failed", "message": "Expected 'plot' to have been called once. Called 0 times.", "passed": false, "points": ["p03-10.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part03-e10_subfigures/test/test_subfigures.py\", line 69, in test_method_calls\n    mysub.ax[0].plot.assert_called_once()\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/mock.py\", line 810, in assert_called_once\n    raise AssertionError(msg)\n"]}]