[{"name": "test.test_almost_meeting_lines.AlmostMeetingLines.test_first", "status": "failed", "message": "(array([[1.],\n       [5.]]), array([], dt[44 chars]44])) != True : Expected exact solution for system (a1=1, b1=4, a2=3, b2=2)!", "passed": false, "points": ["p03-08.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part03-e08_almost_meeting_lines/test/test_almost_meeting_lines.py\", line 38, in test_first\n    self.assertEqual(exact, True, msg=\"Expected exact solution for system %s!\" % system)\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 832, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_almost_meeting_lines.AlmostMeetingLines.test_inconsistent", "status": "failed", "message": "(array([[-2.25],\n       [ 2.25]]), array([], dtype=float64), 1, array([2., 0.])) != False : Did not expect exact solution for inconsistent system (a1=1, b1=4, a2=1, b2=5)!", "passed": false, "points": ["p03-08.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part03-e08_almost_meeting_lines/test/test_almost_meeting_lines.py\", line 59, in test_inconsistent\n    self.assertEqual(exact, False, msg=\"Did not expect exact solution for inconsistent system %s!\" % system)\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 832, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}, {"name": "test.test_almost_meeting_lines.AlmostMeetingLines.test_types", "status": "passed", "message": "", "passed": true, "points": ["p03-08.1"], "backtrace": []}, {"name": "test.test_almost_meeting_lines.AlmostMeetingLines.test_underdetermined", "status": "failed", "message": "(array([[-2.],\n       [ 2.]]), array([], dtype=float64), 1, array([2., 0.])) != False : Did not expect exact solution for underdetermined system (a1=1, b1=4, a2=1, b2=4)!", "passed": false, "points": ["p03-08.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part03-e08_almost_meeting_lines/test/test_almost_meeting_lines.py\", line 51, in test_underdetermined\n    msg=\"Did not expect exact solution for underdetermined system %s!\" % system)\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 839, in assertEqual\n    assertion_func(first, second, msg=msg)\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 832, in _baseAssertEqual\n    raise self.failureException(msg)\n"]}]