[{"name": "test.test_vector_angles.VectorAngles.test_first", "status": "passed", "message": "", "passed": true, "points": ["p02-15.1"], "backtrace": []}, {"name": "test.test_vector_angles.VectorAngles.test_main", "status": "passed", "message": "", "passed": true, "points": ["p02-15.1"], "backtrace": []}, {"name": "test.test_vector_angles.VectorAngles.test_zero", "status": "failed", "message": "\nNot equal to tolerance rtol=1e-07, atol=0.0001\nIncorrect result for vectors [[ 0.98096275 -0.88097463 -0.04622886]\n [ 0.76773404  1.24072655  0.32977086]\n [ 0.21619077  0.01871192  0.09908936]\n [-2.00987555  0.18546183 -0.04379521]\n [ 0.45630975  1.48304518 -0.40406994]\n [-1.38463782  1.25802964 -0.09543996]\n [ 0.88316841  0.34647498  0.92490268]\n [ 1.83438368 -0.97086007  1.45309058]\n [-0.85922881 -0.32218451  0.62708914]\n [ 1.09254096 -1.93241824  1.64882155]] and [[ 0.98096275 -0.88097463 -0.04622886]\n [ 0.76773404  1.24072655  0.32977086]\n [ 0.21619077  0.01871192  0.09908936]\n [-2.00987555  0.18546183 -0.04379521]\n [ 0.45630975  1.48304518 -0.40406994]\n [-1.38463782  1.25802964 -0.09543996]\n [ 0.88316841  0.34647498  0.92490268]\n [ 1.83438368 -0.97086007  1.45309058]\n [-0.85922881 -0.32218451  0.62708914]\n [ 1.09254096 -1.93241824  1.64882155]]!\nx and y nan location mismatch:\n x: array(nan)\n y: array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])", "passed": false, "points": ["p02-15.1"], "backtrace": ["  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 59, in testPartExecutor\n    yield\n", "  File \"/home/vins/anaconda3/lib/python3.7/unittest/case.py\", line 615, in run\n    testMethod()\n", "  File \"/home/vins/TMC/week2/hy-data-analysis-with-python-summer-2019/part02-e15_vector_angles/test/test_vector_angles.py\", line 40, in test_zero\n    err_msg=\"Incorrect result for vectors %s and %s!\" % (A, A))\n", "  File \"/home/vins/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 1501, in assert_allclose\n    verbose=verbose, header=header, equal_nan=equal_nan)\n", "  File \"/home/vins/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 757, in assert_array_compare\n    flagged = func_assert_same_pos(x, y, func=isnan, hasval='nan')\n", "  File \"/home/vins/anaconda3/lib/python3.7/site-packages/numpy/testing/_private/utils.py\", line 733, in func_assert_same_pos\n    raise AssertionError(msg)\n"]}]